branch-defaults:
  default:
    environment: null
  main:
    environment: null
  master:
    environment: fake-news-env
    group_suffix: null
environment-defaults:
  fake-news-env:
    branch: null
    repository: null
global:
  application_name: fake-news-app
  branch: null
  default_ec2_keyname: awskey
  default_platform: Python 3.11
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
